#!/bin/bash

#Voyager 16.04
#Script de metalux basé sur un script original de rodofr
#License GPL

######################
#Internationalisation#
######################

TEXTDOMAIN=${0##*/}
TEXTDOMAINDIR=$(dirname "$0")/locale

##################
#Personnalisation#
##################

#Avertissement-Toujours mettre entre guillemets les chemins vers les images
#==========================================================================

#Ajouter une image à la fenêtre-Ne pas toucher à la seconde ligne.Commenter la seconde ligne avec un # si pas d'image.
image='/.awn1/logo.png'
img="--image="$image""

#Positionne l'image en haut.Pour un affichage sur le côté, commenter la ligne avec un #.
top='--image-on-top'

#Icône de la fenêtre-Ne pas toucher à la seconde ligne.Commenter la seconde ligne avec un # si pas d'icône.
img_ico='/.awn1/logo.png'
ico="--window-icon="$img_ico""

#Titre de la fenêtre
titre='Voyager color'

##################
#Script principal#
##################

#tableau des couleurs
color=( Green Red Blue Grey Violet Orange )
color_translate=( $"Green" $"Red" $"Blue" $"Grey" $"Violet" $"Orange" )

#Creation des boutons 'couleur'
fct () {
color=( Green Red Blue Grey Violet Orange )
eval cp "/.awn1/${color[$1]}/${color[$1]}$2/*" "/.awn1/" && xfce4-panel -r
}
export -f fct

#Creation des onglets
for ((a=1;a<12;a++)); do
    yad --plug=2112 --tabnum=$a  --form --columns=2 --align=center --field="<b><span color='${color[0]}'>${color_translate[0]}</span></b>:fbtn" --field="<b><span color='${color[1]}'>${color_translate[1]}</span></b>:fbtn" --field="<b><span color='${color[2]}'>${color_translate[2]}</span></b>:fbtn" --field="<b><span color='${color[3]}'></span>${color_translate[3]}</b>:fbtn" --field="<b><span color='${color[4]}'>${color_translate[4]}</span></b>:fbtn" --field="<b><span color='${color[5]}'>${color_translate[5]}</span></b>:fbtn" "bash -c 'fct 0 $a'" "bash -c 'fct 1 $a'" "bash -c 'fct 2 $a'" "bash -c 'fct 3 $a'" "bash -c 'fct 4 $a'" "bash -c 'fct 5 $a'" "bash -c 'fct 6 $a'" "bash -c 'fct 7 $a'" "bash -c 'fct 8 $a'" "bash -c 'fct 9 $a'" "bash -c 'fct 10 $a'" "bash -c 'fct 11 $a'" &> /dev/null & 
done

#Fenêtre principale

yad "$img" "$top" "$ico" --borders=20 --text-align=center --text $"<b><big>Choose a color\n</big></b>" --notebook --tab-borders=40 --fixed --center --title="$titre" --key=2112 --tab="Panel Lateral" --tab="Mobility One" --tab="Mobility Two" --tab="Private" --tab="Kodi" --tab="Terminal" --tab="Search" --tab="Backup" --tab="Session" --tab="Calendar" --tab="Logo" --button="gtk-quit:252"

#Fin
exit 0

