#!/bin/bash
# License GPL
# by rodofr Live Voyager
# V3.0 pour Voyager 16.04 par metalux
# Display the action selector

if pgrep gnome-calendar;then
	pkill gnome-calendar
	pkill -f xfce4-notes
    sed -i s"/Hidden=false/Hidden=true/" ~/.config/autostart/xfce4-notes-autostart.desktop
	wmctrl -s0
	exit 0
else	
	wmctrl -s2
	gnome-calendar & xfce4-notes 
	exit 0
fi
exit 0
