#! /bin/bash
box=$(yad --title=Voyager --window-icon="/usr/share/xfce4/voyager/p1.png" --image="/usr/share/xfce4/voyager/Voyager0.png" --image-on-top --separator="" --width=300 --height=240 --list --radiolist --no-headers --column="1" --column="option" --print-column 2 true "Voyager Wall" false "Conky Control" false "Plank Control" false "Colors Icons" false "Reparation" false "Security")

case $box in
    "Voyager Wall")
	bash ~/.scripts/Wall/Voyager_Themes;;
    "Conky Control")
        python3 ~/.scripts/Conky/ConkyControl.py;;
    "Plank Control")
	bash ~/.scripts/plank/Plank1.sh;;
    "Colors Icons")
        bash ~/.scripts/colors/colors;;
    "Reparation")
        bash ~/.scripts/Reparation/Voyager-Projet.sh;;
    "Security")
        bash ~/.scripts/security/secu.sh;;
    *)
        exit 0
esac
exit 0
