#!/bin/bash
# License GPL
# Live Voyager rodofr@
# V3.0 par metalux pour Voyager 16.04


#			==============================================================================================

TEXTDOMAIN=${0##*/}
TEXTDOMAINDIR="$(dirname "$0")/locale"
##########FUNCTIONS############


#-----new theme-----

newtheme () {
	nom=$(yad --entry --title $"New theme" --text $"Theme name") && [[ -n "$nom" ]]
	while [[ -e $HOME/.scripts/Wall/themes/"$nom" ]];do
		yad --warning --text=$"This theme already exists, please choose another name" && nom=$(yad --entry --title $"New theme" --text $"Theme name") && [[ -n "$nom" ]]
	done		
	touch $HOME/.scripts/Wall/themes/"$nom"
	for (( a=1; a<=6; a++ ))
		do
			b=$a
			[[ $a -eq 1 ]] && (pgrep xfce4-notifyd && pkill xfce4-notifyd) && notify-send -t 30000 -i notification-message-im $"Select Image Wall 1"
			[[ $a -eq 2 ]] && (pgrep xfce4-notifyd && pkill xfce4-notifyd) && notify-send -t 30000 -i notification-message-im $"Select Image Wall 2"
			[[ $a -eq 3 ]] && (pgrep xfce4-notifyd && pkill xfce4-notifyd) && notify-send -t 30000 -i notification-message-im $"Select Image Wall 3"
			[[ $a -eq 4 ]] && (pgrep xfce4-notifyd && pkill xfce4-notifyd) && notify-send -t 30000 -i notification-message-im $"Select Image Wall 4"
			[[ $a -eq 5 ]] && b=' Voyager file manager' && pgrep xfce4-notifyd && pkill xfce4-notifyd && notify-send -t 30000 -i notification-message-im $"Select Image Voyager file manager"
			[[ $a -eq 6 ]] && b=' Voyager Terminal' && pgrep xfce4-notifyd && pkill xfce4-notifyd && notify-send -t 30000 -i notification-message-im $"Select Image Voyager Terminal"
			create=$(yad --file-selection --width=450 --height=400 --filename="$HOME/Images/" --title $"Selection Wall$b")
			[[ $? -ne 0 ]] && rm $HOME/.scripts/Wall/themes/"$nom" && (pgrep xfce4-notifyd && pkill xfce4-notifyd) && notify-send $"Cancellation" && exit 1
			[[ -z "$create" ]] && exit 1
			mime=$(file -b --mime-type "${create}")
			until [[ "$mime" == "image/jpeg" ]] || [[ "$mime" == "image/png" ]];do
				yad --warning --text=$"This image file is not valid" && (( a-- )) && break
			done
			echo $create >> $HOME/.scripts/Wall/themes/"$nom"
		done
		chemin="$HOME/.scripts/Wall/themes/" && config
}

#-----Theme modification-----

config () {
	selection=null
	while [[ $? -eq 0 ]]; do
	ls "$chemin" > .voythem
	if [[ -z $(<.voythem) ]];then
		yad --warning --text=$"No custom theme available. Please create one then try again."
		[[ $? -ne 0 ]] && exit 1
		 newtheme
	else
    		a=0
		while read ligne
		do
			(( a++ ))
    			liste[$a]=$(echo $ligne) 
		done < .voythem
		if choix=$(yad --sticky --window-icon=/usr/share/xfce4/voyager/v1.png --no-headers --image=/usr/share/xfce4/voyager/Voyager.png --separator="" --button=$"Preview:0" --button="gtk-ok:1" --button="gtk-cancel:252" --list --width=500 --height=370 --title=$"Voyager themes" --text=$"Theme choice" --column $"Themes" "${liste[@]}"); then
			a=0
	for (( a=1; a<=4; a++ ))
	do
   		clef[$a]="/backdrop/screen0/monitor0/workspace$(( $a - 1 ))/last-image"
		xfconf-query -c xfce4-desktop -p ${clef[$a]} >> $HOME/.scripts/Wall/.sauvegarde
	done
	for (( a=5; a<=6; a++ ))
	do
		sed -n "/wall=/p" $HOME/.scripts/Wall/wall$a | cut -d "\"" -f5 | sed "s/.$//" >> $HOME/.scripts/Wall/.sauvegarde
	done
		a=0
			while read ligne
				do
					(( a++ ))
   					video[$a]="/backdrop/screen0/monitor0/workspace$(( $a - 1 ))/last-image"
   					video2[$a]=$(echo $video | sed 's/\//\\\//g')
					[[ $a -ge 7 ]] && break
						if [[ $a -le 4 ]];then
							xfconf-query -c xfce4-desktop -p "${video[$a]}" -s "$ligne"
							echo "$ligne" > ~/.scripts/Wall/.fondbase$a
						else
							echo "$ligne" > ~/.scripts/Wall/.fondbase$a	
						fi
				done < "$chemin$choix"
		rm .voythem
		pgrep xfce4-notifyd && pkill xfce4-notifyd
		notify-send -i ~/.scripts/Wall/Voyager.png -t 9000000 $"Voyager themes" $"Testing \" $choix \". Press the Select button to confirm this choice."
		elif [[ $? -eq 252 ]]; then
			a=0
			while read ligne
				do
					(( a++ ))
   					video[$a]="/backdrop/screen0/monitor0/workspace$(( $a - 1 ))/last-image"
   					video2[$a]=$(echo $video | sed 's/\//\\\//g')
					[[ $a -ge 7 ]] && break
						if [[ $a -le 4 ]];then
							xfconf-query -c xfce4-desktop -p "${video[$a]}" -s "$ligne"
							echo "$ligne" > ~/.scripts/Wall/.fondbase$a
						else
							echo "$ligne" > ~/.scripts/Wall/.fondbase$a	
						fi
				done < $HOME/.scripts/Wall/.sauvegarde
			rm $HOME/.scripts/Wall/.sauvegarde
			pgrep xfce4-notifyd && pkill xfce4-notifyd
			notify-send -i ~/.scripts/Wall/Voyager.png $"Voyager themes" $"Choice canceled. No new theme installed." && rm .voythem && exit 0
		else
			rm $HOME/.scripts/Wall/.sauvegarde
			pgrep xfce4-notifyd && pkill xfce4-notifyd
			notify-send -i ~/.scripts/Wall/Voyager.png $"Voyager themes" $"Theme \"$selection\" theme selected" && rm .voythem && exit 0
		fi
	fi

	selection=$choix
	done
}


#                        =====================================================================


choixtheme=$(yad --window-icon=/usr/share/xfce4/voyager/v2.png --image=/usr/share/xfce4/voyager/Voyager2.png --no-headers --list --radiolist --width=500 --height=190 --separator="" --print-column=2 --title=$"Voyager themes" --text=$"Theme choice" --column=$"Choice" --column=$"Themes" TRUE $"Voyager themes" "" $"Custom themes" "" $"Save current configuration"  "" $"New theme" "" $"Delete a theme") && [[ -n $choixtheme ]]
if [[ "$choixtheme" == $"Voyager themes" ]];then
	chemin="$HOME/.scripts/Wall/themes/.defaut/" && config
elif [[ "$choixtheme" == $"Custom themes" ]];then
	chemin="$HOME/.scripts/Wall/themes/" && config 
elif [[ "$choixtheme" == $"Save current configuration" ]];then
	nom=$(yad --entry --title $"New theme" --text $"Theme name") && [[ -n "$nom" ]]
	while [[ -e $HOME/.scripts/Wall/themes/"$nom" ]];do
		yad --warning --text=$"This theme already exists, please choose another name." && nom=$(yad --entry --title $"New theme" --text $"Theme name") && [[ -n "$nom" ]]
	done
	touch $HOME/.scripts/Wall/themes/"$nom"
	a=0
	for (( a=1; a<=4; a++ ))
	do
   		clef[$a]="/backdrop/screen0/monitor0/workspace$(( $a - 1 ))/last-image"
		xfconf-query -c xfce4-desktop -p ${clef[$a]} >> $HOME/.scripts/Wall/themes/"$nom"
	done
	for (( a=5; a<=6; a++ ))
	do
		sed -n "/wall=/p" $HOME/.scripts/Wall/wall$a | cut -d "\"" -f5 | sed "s/.$//" >> $HOME/.scripts/Wall/themes/"$nom"
	done
	notify-send -i ~/.scripts/Wall/Voyager.png $"Voyager themes" $"Theme $nom successfully saved" 						
elif [[ $choixtheme == $"New theme" ]];then
	newtheme
elif [[ $choixtheme == $"Delete a theme" ]];then
	ls $HOME/.scripts/Wall/themes > .voythem
	if [[ -z $(<.voythem) ]];then
		yad --warning --timeout=5 --text=$"No theme to delete"
	else
		choix=$(for (( x=1 ; x<=$(wc -l < .voythem) ; x++ ))
			do
				echo FALSE
				echo "$(sed -n "${x}p" .voythem)"
			done | yad --window-icon=/usr/share/xfce4/voyager/v2.png --image=/usr/share/xfce4/voyager/Voyager2.png --no-headers --list  --checklist --width=450 --height=320 --title=$"Choice :" --column=$"choice :" --column=$"Themes")
			IFS='|'
			for i in $choix
			do
				rm $HOME/.scripts/Wall/themes/"$i"
			done
			unset IFS
			rm .voythem
	fi
else
	exit 0 
fi
#fin
exit 0
