#!/bin/bash
# License GPL
# by rodofr Live Voyager
# V3 pour Voyager 16.04 par metalux
# Display the action selector

current_desktop=$(wmctrl -d | awk '$2=="*" {print $1}')
	if xwininfo -name 'Voyager Terminator';then
	if [[ $current_desktop -ne 1 ]];then
		wmctrl -s1
		exit 0
	else
		wmctrl -s0
		wmctrl -c 'Voyager Terminator'
	fi
else
	wmctrl -s1
	terminator -T 'Voyager Terminator' -mb --layout=h -p 'voyager'	
fi
exit 0
