#!/bin/bash
# License GPL
# by rodofr Live Voyager
# V3.0 par metalux pour Voyager 16.04
# Display the action selector

[[ ! $(wmctrl -d | awk '$2=="*" {print $1}') -eq 0 ]] && wmctrl -s0 &
if [ ! -z "$1" ];then
    xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$1"
    echo $1 > ~/.scripts/Wall/.fondbase1
fi
exit 0
