#!/bin/bash

####################################################################################
#
# MultiScript : Fichiers Images
# Permet de travailler sur des photos venant d'APN (renommer, classer, etc...)
#
# Dépendances :
# zenity jhead exiv2 imagemagick sed libimage-exiftool-perl
#
# Version :
# 0.3.5 2011/12/03
## Ajout de la fonction : Rajouter un intitulé devant le nom du fichier et renommer sur 2 chiffres
## Correction de la fonction : Générer un fichier pdf optimisé des photos
## Corrections mineures
#
# 0.3.4 2011/02/22
# 0.3 : 2010/06/10
# 0.2 : 2010/04/27 (version non distribuée)
# 0.1 : 2010/04/01
#
# Utilisation :
# Se placer dans le répertoire contenant les photos à traiter, lancer le script.
# Inutile de sélectionner les photos, le script va travailler sur toutes les photos
# contenues dans le répertoire (et uniquement dans le répertoire, il n'est pas récursif)
#
# Le script travaille beaucoup sur les données exif des photos,
# donc si celles ci sont fausses le résultat ne sera pas terrible ;)
#
# Le script travaille en modifiant la casse des extensions des fichiers (majuscule en minuscule), c'est voulu
# si ce comportement ne vous convient pas, n'utilisez pas ce script, ou modifiez-le ;)
#
# Prenez l'habitude de faire des manips sur des copies de fichiers
#
# Le fil de discussion sur le forum d'Ubuntu fr : 
# http://forum.ubuntu-fr.org/viewtopic.php?pid=3371321
#
# L'historique du script :
# http://soupaloignon.net/web/articles/articles.php?id=28&cat=3
#
# Testé sous Mint 9 (Lucid)
#
# www.soupaloignon.net
####################################################################################


####################################################################################
###### Mettre tout le script dans une boucle #######################################

while [ "$fin_du_script" != "oui" ]
do
####################################################################################


####################################################################################
###### Variable(s) générale(s) #####################################################

# Titre des fenêtres zenity
title="MultiScript : Fichiers photos (V 0.3.5)"

####################################################################################


####################################################################################
###### Function(s) #################################################################

function Casse-Extension
{
    # Transforme la casse et ou l'extension en jpg
ls -d *.JPG | sed 's/\(.*\).JPG$/mv "&" "\1.jpg"/' | sh
ls -d *.JPEG  | sed 's/\(.*\).JPEG$/mv "&" "\1.jpg"/' | sh
ls -d *.jpeg  | sed 's/\(.*\).jpeg$/mv "&" "\1.jpg"/' | sh

# Transforme la casse en png
ls -d *.PNG | sed 's/\(.*\).PNG$/mv "&" "\1.png"/' | sh
}
####################################################################################



####################################################################################
###### Afficher le menu ############################################################
            
    menu=`zenity --width=750 --height=800 \
    --title "$title" --text="Choisir l'action à effectuer" --list --hide-column 1 --column "" --column "" \
    0 "QUITTER LE SCRIPT (V 0.3.5)" \
    1 "" \
    2 "Ranger des photos en vrac dans des dossiers datés (année, mois, jour) (jpg)" \
    21 "" \
    3 "Changer la casse : JPG, JPEG, jpeg => jpg / PNG => png" \
    31 "Effacer TOUS les tags EXIF et IPTC (partiel) sur une copie du dossier (jpg)" \
    32 "" \
    4 "Rajouter un intitulé devant le nom du fichier (jpg et png)" \
    41 "Rajouter un intitulé à la fin du nom du fichier (jpg et png)" \
    5 "Renommer en masse sur X chiffres au choix (jpg et png)" \
    9 "Renommer dans l'ordre chronologique des photos venant d'APN différents (jpg)"\
        51 "Rajouter un intitulé devant le nom du fichier et renommer sur 2 chiffres (jpg et png)"\
    52 "" \
    6 "Générer un fichier pdf optimisé des photos (800 X 600) du répertoire (jpg et png)" \
    7 "Générer une planche contact en .jpg des images du répertoire (jpg et png)" \
    81 "" \
    10 "Changer la date : Année et/ou mois et/ou jour (heures/minutes/secondes non changés) (jpg)" \
    11 "Changer la date et l'heure (Heures, minutes et secondes seront les mêmes pour toutes les photos)(jpg)" \
    12 "Avancer ou reculer les heures et/ou minutes et/ou secondes (jpg)" \
    13 "Voir les champs dates des données Exif (jpg)" \
    131 "" \
    14 "Convertir les jpg en png (n'efface pas les originaux)" \
    15 "Convertir les png en jpg (80%) (n'efface pas les originaux)" \
    8 "Créer un dossier contenant une copie des photos, retaillées (jpg et png)" \
    16 "" \
    17 "A LIRE" \     
    | sed 's/ max//g' `

# Pour quitter
    if [ "$menu" = 0 ] ; then
    fin_du_script="oui"
    fi 

# Vérifier qu'un choix a été fait
    if [ ! "$menu" ]; then
    zenity --error --title="Erreur" --text="Choisissez une action"
    fi
####################################################################################

####################################################################################
###### Ranger des photos en vrac dans des dossiers datés (année, mois, jour) #######

# Choix du menu
if [ "$menu" = 2 ] ; then

# Eviter les problèmes avec des noms de fichiers comportants des espaces
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

exiftool -r *.jpg '-FileName<${DateTimeOriginal}' -d "%Y-%m-%d/"

fi
####################################################################################
   
####################################################################################
###### Changer la casse ############################################################ 

# Choix du menu 
if [ "$menu" = 3 ] ; then 
 
# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

fi
####################################################################################

####################################################################################
###### Effacer EXIF et IPTC ######################################################## 

# Choix du menu 
if [ "$menu" = 31 ] ; then 
 
# Eviter les problèmes avec des noms de fichiers comportants des espaces
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Création du répertoire / copie / se placer dans le repertoire
REP="No-EXIF"
mkdir $REP
cp -r *jpg $REP
cd $REP
exiv2 -d a *.jpg

fi
####################################################################################

####################################################################################
###### Rajouter un intitulé devant le nom du fichier ############################### 

# Choix du menu 
if [ "$menu" = 4 ] ; then 

# Eviter les problemes avec des noms comportant des espaces 
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

## Texte à rajouter devant le nom du fichier
TEXTE=$(zenity --entry --width=500 --height=150 --title="$title : Intitulé devant le nom de fichier" --entry-text="" --text="Entrez le nom à rajouter devant vos fichiers :")
         if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi
# Boucle d'insertion
for fichier in `ls *.jpg *.png` 
do 
rename 's/^/'$TEXTE'/' $fichier
done

fi
####################################################################################


####################################################################################
###### Rajouter un intitulé à la fin du nom du fichier ############################### 

# Choix du menu 
if [ "$menu" = 41 ] ; then 

# Eviter les problemes avec des noms comportant des espaces 
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

## Texte à rajouter à la fin du nom du fichier
TEXTEFIN=$(zenity --entry --width=500 --height=150 --title="$title : Intitulé à la fin du nom du fichier" --entry-text="" --text="Entrez l'intitulé à rajouter à la fin de chaque nom de fichier :")
         if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

for file in *jpg *.png
do
base=`basename $file`
mv $file  ${base%.*}$TEXTEFIN.${base##*.}
done


fi
####################################################################################


####################################################################################
###### Renomme en masse sur X chiffres #############################################
 
# Choix du menu   
if [ "$menu" = 5 ] ; then  

# Choix du nombre de caracteres
nombre=$(zenity --entry --width=500 --height=150 --title="$title : Nombre de chiffres" --entry-text="2" --text="Choisir sur quel nombre de chiffres seront renommés vos fichiers :" )


if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Boucle
let "indice=1"
for fichier in *.jpg *.png
do
         if [ -f "$fichier" ]; then
            extension=${fichier##*.}
            echo "$fichier" "=>" "$indice.$extension"
            mv "$fichier" `printf "%0"$nombre"d" $indice`".$extension"
            let "indice+=1"
        fi
done






fi
####################################################################################


####################################################################################
###### Génére un fichier pdf des photos du répertoire ##############################

# Choix du menu
if [ "$menu" = 6 ] ; then

# Nom du pdf
TEMPORAIRE='temporaire.pdf'
NOM='00-final.pdf'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Boucle
for i in "*.jpg *.png"
do
 #convert $i -quality 80 -geometry 800x600 +compress $TEMPORAIRE
 convert $i +compress $TEMPORAIRE
 gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=$NOM $TEMPORAIRE
 rm $TEMPORAIRE
done

#-geometry a la place de -resize
#convert * fichier.pdf ==> respecte le rtatio de sphotos


fi
# Plus de détails sur cette portion de script :
# http://forum.ubuntu-fr.org/viewtopic.php?pid=2966157
####################################################################################


####################################################################################
###### Génére une planche contact en .jpg des images du répertoire (jpg et png)#####

# Choix du menu
if [ "$menu" = 7 ] ; then

# Nom du fichier final
NOM='00-planche-contact.jpg'

# Eviter les problèmes avec des noms de fichiers comportants des espaces
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Go ;)
montage -label '%f' *.jpg *.png \
-tile 6x7 $NOM

fi
####################################################################################


####################################################################################
###### Créer un dossier contenant une copie des photos, retaillées #################

# Choix du menu
if [ "$menu" = 8 ] ; then

IFS="|"
    #title="Choix de la taille"
    VALEUR=`zenity --title "$title : Retailler des photos"  --text "Choisir la nouvelle taille des photos" --list --separator=" "  --height=250 --width=500 --column="Taille" "320x240" "450x338" "640x480" "800x600" "1024x768" | sed 's/ max//g' `
    # click sur le bouton abandon
        if [ "$?" != 0 ] ; then
        exit
        fi
    # si pas de taille sélectionnée
        if [ ! "$VALEUR" ]; then
        zenity --error --title="error" --text="Aucune taille n'a été sélectionnée. Sortie de cette option."
        fi

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Création du répertoire / copie / se placer dans le repertoire
mkdir $VALEUR
cp -r *jpg *.png $VALEUR
cd $VALEUR

# Retailler à la valeur choisie
mogrify -quality 60 -resize $VALEUR *.jpg *.png
# 

fi
####################################################################################


####################################################################################
###### Renomme dans l'ordre chronologique des photos venant d'APN différents (jpg) #
###### par la date-heures-secondes de prise de vue #################################

# Choix du menu
if [ "$menu" = 9 ] ; then 

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Renomme par date et heure exif (donc dans l'ordre chronologique)
# tous appareils confondus
exiv2 -r %Y-%m-%d--%Hh-%Mm-%Ss mv *.jpg

fi
####################################################################################


####################################################################################
###### Rajouter un intitulé devant le nom du fichier et renommer sur 2 chiffres) ##


# Choix du menu
if [ "$menu" = 51 ] ; then 

if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

## Texte à rajouter devant le nom du fichier
TEXTE=$(zenity --entry --width=500 --height=150 --title="$title : Intitulé devant le nom de fichier" --entry-text="" --text="Entrez le nom à rajouter devant vos fichiers :")

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Boucle
let "indice=1"
for fichier in *.jpg *.png
do
         if [ -f "$fichier" ]; then
            extension=${fichier##*.}
            echo "$fichier" "=>" "$indice.$extension"
            mv "$fichier" `printf "%0"2"d" $indice`".$extension"
            let "indice+=1"
        fi
done

# Boucle d'insertion
for fichier in `ls *.jpg *.png` 
do 
rename 's/^/'$TEXTE'/' $fichier
done




fi
####################################################################################





####################################################################################
###### Changer la date : Année et/ou mois et/ou jour ###############################
###### (heures/minutes/secondes non changés) (jpg) #################################
    
# Choix du menu
if [ "$menu" = 10 ] ; then    

## Entrer la date
DATE=$(zenity --entry --width=300 --height=150 --title="Date" --entry-text="" --text="Entrez la nouvelle date :\n\nDans un format AAAA pour ne changer que l'année\n(mois/jour/heures/minutes/secondes non changés)\n\nDans un format AAAA:MM pour ne changer que l'année et le mois\n(jour/heures/minutes/secondes non changés)\n\nDans un format AAAA:MM:JJ pour ne changer que l'année, le mois et le jour\n(heures/minutes/secondes non changées)\n\nAttention à bien mettre le \":\" (sans les guillements) entre les valeurs si nécessaire" )

         if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Go
jhead -ds$DATE *jpg

fi
####################################################################################


####################################################################################
###### Changer la date et l'heure (jpg) ############################################
  
# Choix du menu  
if [ "$menu" = 11 ] ; then  

## Entrer la date
DATE=$(zenity --entry --width=300 --height=150 --title="Date" --entry-text="2010:10:10" --text="Entrez la date dans un format AAAA:MM:JJ" )
         if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

## Entrer l'heure
HEURE=$(zenity --entry --width=300 --height=150 --title="Heure" --entry-text="10:10:10" --text="Entrez la date dans un format HH:MM:SS" )
        if [ "${PIPESTATUS[0]}" != "0" ]; then
         exit
      fi

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Go
exiv2 -M"set Exif.Image.DateTime $DATE $HEURE" -M"set Exif.Photo.DateTimeOriginal $DATE $HEURE" -M"set Exif.Photo.DateTimeDigitized $DATE $HEURE" *.jpg

fi
####################################################################################


####################################################################################
###### Changer les heures : En positif ou négatif ###############################

    
# Choix du menu
if [ "$menu" = 12 ] ; then    

## Entrer la valeur à rajouter ou retrancher
TEMPS=$(zenity --entry --width=300 --height=150 --title="Avancer ou reculer : Heure / Minute / Seconde" --entry-text="" --text="Entrez tout d'abord le symbole + ou - (pour rajouter ou enlever du temps) puis les valeurs de temps :\n\n+10 rajoutera 10 heures\n-10 enlévera 10 heures\n+00:10 rajoutera 10 minutes\n+00:00:10 rajoutera 10 secondes\n\nAttention à bien mettre le \":\" (sans les guillements) entre les valeurs si nécessaire" )

         if [ "${PIPESTATUS[0]}" != "0" ]; then
           exit
         fi

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Go
jhead -ta$TEMPS *.jpg

fi
####################################################################################

####################################################################################
###### Voir les champs dates exif (jpg) ############################################
    
# Choix du menu 
if [ "$menu" = 13 ] ; then  

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

# Go
#exiv2 -Plt *.jpg | sed -n '/Date and Time/p' | zenity --text-info --title ="exif" --width=700 --height=500
exiv2 -Plt *.jpg | sed -n '/Date*/p' | zenity --text-info --title ="exif" --width=700 --height=500

fi
####################################################################################


####################################################################################
###### jpg en png ##################################################################

# Choix du menu
if [ "$menu" = 14 ] ; then

# Eviter les problèmes avec des noms de fichiers comportants des espaces
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

for file in *.jpg; do convert "$file" "$(basename $file .jpg).png"; done

mkdir png
mv *.png png

fi
####################################################################################


####################################################################################
###### Créer un dossier contenant une copie des photos png au format jpg ###########

# Choix du menu
if [ "$menu" = 15 ] ; then

# Eviter les problèmes avec des noms de fichiers comportants des espaces
IFS=$'\n'

# Function Transforme la casse et ou l'extension en jpg/png
Casse-Extension

for file in *.png; do convert -quality 80 "$file" "$(basename $file .png).jpg"; done

mkdir jpg
mv *.jpg jpg

fi
####################################################################################


####################################################################################
###### A LIRE ######################################################################

# Choix du menu 
if [ "$menu" = 17 ] ; then  

zenity --info --width=500 --height=150 --title="$title : Informations" --text="Merci d'utiliser ce script. Si vous avez des idées d'amélioration, voici le forum où cela se passe :\nhttp://forum.ubuntu-fr.org/viewtopic.php?pid=3371321\n\nCe script travaille sur des images en jpg et/ou png. C'est précisé à la fin de chaque fonction.\n\nTravaillant nativement sur des extensions en .jpg et/ou .png, ce script changera automatiquement la casse de ces 2 extensions s'il rencontre des majuscules dans les fichiers à traiter.\n\nwww.soupaloignon.net"

fi
########################################################################


done 
exit 0