#!/bin/bash
#
# Renommer en masse des DivX avec des noms àlc :
#

rename 's/\ /_/g' *.avi
rename 's/www//g' *.avi
rename 's/Torrent//g' *.avi
rename 's/_Ox.com//g' *.avi
rename 's/Gk.cx//g' *.avi
rename 's/_9.cz_//g' *.avi
rename 's/_9.tv_//g' *.avi
rename 's/_Gk.tv_//g' *.avi
rename 's/.9.uno//g' *.avi
rename 's/FRENCH//g' *.avi
rename 's/_1080p//g' *.avi
rename 's/720p//g' *.avi
rename 's/HDRiP//g' *.avi
rename 's/BluRay//g' *.avi
rename 's/-EXTREME//g' *.avi
rename 's/2019//g' *.avi
rename 's/x264//g' *.avi
rename 's/_ac3//g' *.avi
rename 's/\[//g' *.avi
rename 's/\]//g' *.avi
rename 's/^_//' *.avi
rename 's/^_//' *.avi
rename 's/^_//' *.avi
rename 's/^_//' *.avi
rename 's/BDRip.//g' *.avi
rename 's/XviD.//g' *.avi
rename 's/AC3.//g' *.avi
rename 's/IMAX.//g' *.avi
rename 's/TRUE.//g' *.avi
rename 's/-FuN//g' *.avi
rename 's/DvDrip//g' *.avi
rename 's/H264//g' *.avi
rename 's/WEB.//g' *.avi
rename 's/DL.//g' *.avi
rename 's/1080p.//g' *.avi
rename 's/HDLight.//g' *.avi
rename 's/Truefrench.//g' *.avi
rename 's/ac3.//g' *.avi
rename 's/DTS.//g' *.avi
rename 's/DVDRip//g' *.avi
rename 's/TRUE.//g' *.avi
rename 's/_-_//g' *.avi
rename 's/__//g' *.avi
rename 's/__//g' *.avi
rename 's/__//g' *.avi
rename 's/__//g' *.avi
rename 's/\.\././g' *.avi
rename 's/\.\././g' *.avi
rename 's/\.\././g' *.avi
rename 's/\.\././g' *.avi


rename 's/\ /_/g' *.mkv
rename 's/www//g' *.mkv
rename 's/Torrent//g' *.mkv
rename 's/_Ox.com//g' *.mkv
rename 's/Gk.cx//g' *.mkv
rename 's/_9.cz_//g' *.mkv
rename 's/_9.tv_//g' *.mkv
rename 's/_Gk.tv_//g' *.mkv
rename 's/.9.uno//g' *.mkv
rename 's/FRENCH//g' *.mkv
rename 's/_1080p//g' *.mkv
rename 's/720p//g' *.mkv
rename 's/HDRiP//g' *.mkv
rename 's/BluRay//g' *.mkv
rename 's/-EXTREME//g' *.mkv
rename 's/2019//g' *.mkv
rename 's/x264//g' *.mkv
rename 's/_ac3//g' *.mkv
rename 's/\[//g' *.mkv
rename 's/\]//g' *.mkv
rename 's/^_//' *.mkv
rename 's/^_//' *.mkv
rename 's/^_//' *.mkv
rename 's/^_//' *.mkv
rename 's/BDRip.//g' *.mkv
rename 's/XviD.//g' *.mkv
rename 's/AC3.//g' *.mkv
rename 's/IMAX.//g' *.mkv
rename 's/TRUE.//g' *.mkv
rename 's/-FuN//g' *.mkv
rename 's/DvDrip//g' *.mkv
rename 's/H264//g' *.mkv
rename 's/WEB.//g' *.mkv
rename 's/DL.//g' *.mkv
rename 's/1080p.//g' *.mkv
rename 's/HDLight.//g' *.mkv
rename 's/Truefrench.//g' *.mkv
rename 's/ac3.//g' *.mkv
rename 's/DTS.//g' *.mkv
rename 's/DVDRip//g' *.mkv
rename 's/TRUE.//g' *.mkv
rename 's/_-_//g' *.mkv
rename 's/__//g' *.mkv
rename 's/__//g' *.mkv
rename 's/__//g' *.mkv
rename 's/__//g' *.mkv
rename 's/\.\././g' *.mkv
rename 's/\.\././g' *.mkv
rename 's/\.\././g' *.mkv
rename 's/\.\././g' *.mkv


rename 's/\ /_/g' *.mp4
rename 's/www//g' *.mp4
rename 's/Torrent//g' *.mp4
rename 's/_Ox.com//g' *.mp4
rename 's/Gk.cx//g' *.mp4
rename 's/_9.cz_//g' *.mp4
rename 's/_9.tv_//g' *.mp4
rename 's/_Gk.tv_//g' *.mp4
rename 's/.9.uno//g' *.mp4
rename 's/FRENCH//g' *.mp4
rename 's/_1080p//g' *.mp4
rename 's/720p//g' *.mp4
rename 's/HDRiP//g' *.mp4
rename 's/BluRay//g' *.mp4
rename 's/-EXTREME//g' *.mp4
rename 's/2019//g' *.mp4
rename 's/x264//g' *.mp4
rename 's/_ac3//g' *.mp4
rename 's/\[//g' *.mp4
rename 's/\]//g' *.mp4
rename 's/^_//' *.mp4
rename 's/^_//' *.mp4
rename 's/^_//' *.mp4
rename 's/^_//' *.mp4
rename 's/BDRip.//g' *.mp4
rename 's/XviD.//g' *.mp4
rename 's/AC3.//g' *.mp4
rename 's/IMAX.//g' *.mp4
rename 's/TRUE.//g' *.mp4
rename 's/-FuN//g' *.mp4
rename 's/DvDrip//g' *.mp4
rename 's/H264//g' *.mp4
rename 's/WEB.//g' *.mp4
rename 's/DL.//g' *.mp4
rename 's/1080p.//g' *.mp4
rename 's/HDLight.//g' *.mp4
rename 's/Truefrench.//g' *.mp4
rename 's/ac3.//g' *.mp4
rename 's/DTS.//g' *.mp4
rename 's/DVDRip//g' *.mp4
rename 's/TRUE.//g' *.mp4
rename 's/_-_//g' *.mp4
rename 's/__//g' *.mp4
rename 's/__//g' *.mp4
rename 's/__//g' *.mp4
rename 's/__//g' *.mp4
rename 's/\.\././g' *.mp4
rename 's/\.\././g' *.mp4
rename 's/\.\././g' *.mp4
rename 's/\.\././g' *.mp4


rename 's/\ /_/g' *.webm
rename 's/www//g' *.webm
rename 's/Torrent//g' *.webm
rename 's/_Ox.com//g' *.webm
rename 's/Gk.cx//g' *.webm
rename 's/_9.cz_//g' *.webm
rename 's/_9.tv_//g' *.webm
rename 's/_Gk.tv_//g' *.webm
rename 's/.9.uno//g' *.webm
rename 's/FRENCH//g' *.webm
rename 's/_1080p//g' *.webm
rename 's/720p//g' *.webm
rename 's/HDRiP//g' *.webm
rename 's/BluRay//g' *.webm
rename 's/-EXTREME//g' *.webm
rename 's/2019//g' *.webm
rename 's/x264//g' *.webm
rename 's/_ac3//g' *.webm
rename 's/\[//g' *.webm
rename 's/\]//g' *.webm
rename 's/^_//' *.webm
rename 's/^_//' *.webm
rename 's/^_//' *.webm
rename 's/^_//' *.webm
rename 's/BDRip.//g' *.webm
rename 's/XviD.//g' *.webm
rename 's/AC3.//g' *.webm
rename 's/IMAX.//g' *.webm
rename 's/TRUE.//g' *.webm
rename 's/-FuN//g' *.webm
rename 's/DvDrip//g' *.webm
rename 's/H264//g' *.webm
rename 's/WEB.//g' *.webm
rename 's/DL.//g' *.webm
rename 's/1080p.//g' *.webm
rename 's/HDLight.//g' *.webm
rename 's/Truefrench.//g' *.webm
rename 's/ac3.//g' *.webm
rename 's/DTS.//g' *.webm
rename 's/DVDRip//g' *.webm
rename 's/TRUE.//g' *.webm
rename 's/_-_//g' *.webm
rename 's/__//g' *.webm
rename 's/__//g' *.webm
rename 's/__//g' *.webm
rename 's/__//g' *.webm
rename 's/\.\././g' *.webm
rename 's/\.\././g' *.webm
rename 's/\.\././g' *.webm
rename 's/\.\././g' *.webm



