#!/bin/bash

chown guillaume:connaispas "./Aventure/L_Odyssee.avi"

chown guillaume:connaispas "./Deutsches/Thursday_ein_moerderischer_Tag.avi"
chown guillaume:connaispas "./Deutsches/Ab.in.den.Knast.avi"
chown guillaume:connaispas "./Deutsches/Sherlock"
chown guillaume:connaispas "./Deutsches/Sherlock/Sherlock_cd2.avi"
chown guillaume:connaispas "./Deutsches/Sherlock/Sherlock_cd1.avi"
chown guillaume:connaispas "./Deutsches/Bank Job.avi"
chown guillaume:connaispas "./Deutsches/Cargo.avi"
chown guillaume:connaispas "./Deutsches/Keinohrhasen.avi"
chown guillaume:connaispas "./Deutsches/Get_Smart.avi"
chown guillaume:connaispas "./Deutsches/FiNE-Untraceable.avi"

chown guillaume:connaispas "./Documentaires/La_Planete_Blanche.avi"
chown guillaume:connaispas "./Documentaires/Quand c'est gratuit, qui paye.flv"
chown guillaume:connaispas "./Documentaires/Une autre histoire de l’Amérique, par Oliver Stone – La seco.mp4"
chown guillaume:connaispas "./Documentaires/L_Odysseee_de_l_Empathie.avi"
chown guillaume:connaispas "./Documentaires/Antartica.avi"
chown guillaume:connaispas "./Documentaires/Rien_a_Cacher.mp4"
chown guillaume:connaispas "./Documentaires/nuit+et+brouillard.avi"
chown guillaume:connaispas "./Documentaires/Avant le Déluge documentaire intégral - National Geographic .mp4"
chown guillaume:connaispas "./Documentaires/Fukushima, ils mentent au monde entier - K. Idogawa 24.04.14.aac"
chown guillaume:connaispas "./Documentaires/Albert Einstein en 44 minutes (France 5 - BBC).mp4"
chown guillaume:connaispas "./Documentaires/Hubble.avi"
chown guillaume:connaispas "./Documentaires/apollo11_press_conference.wmv"
chown guillaume:connaispas "./Documentaires/Le_Dernier_Trappeur.avi"
chown guillaume:connaispas "./Documentaires/Oceans.avi"
chown guillaume:connaispas "./Documentaires/Envoyé spécial Lactalis le beurre et l'argent du beurre.mp4"
chown guillaume:connaispas "./Documentaires/KENY ARKANA - Un Autre Monde Est Possible - Anti Mondialisation - Anti libéralisme - Altermondialiste - Anti capitalisme.avi"
chown guillaume:connaispas "./Documentaires/UNE ENERGIE A L'INFINIE DEVOILEE.mp4"
chown guillaume:connaispas "./Documentaires/Ken O'Keefe & Ronald Bernard - La vérité sur le système financier (vostfr)-Y_Kr54pebg4.mp4"
chown guillaume:connaispas "./Documentaires/Cowspiracy.mp4"
chown guillaume:connaispas "./Documentaires/Insoumise la France-.mp4"
chown guillaume:connaispas "./Documentaires/Le_Syndrome_du_Titanic.avi"
chown guillaume:connaispas "./Documentaires/Informaction"
chown guillaume:connaispas "./Documentaires/Informaction/partie3"
chown guillaume:connaispas "./Documentaires/Informaction/partie7"
chown guillaume:connaispas "./Documentaires/Informaction/partie8"
chown guillaume:connaispas "./Documentaires/Informaction/partie5"
chown guillaume:connaispas "./Documentaires/Informaction/partie9"
chown guillaume:connaispas "./Documentaires/Informaction/partie4"
chown guillaume:connaispas "./Documentaires/Informaction/partie1"
chown guillaume:connaispas "./Documentaires/Informaction/partie6"
chown guillaume:connaispas "./Documentaires/Informaction/partie2"
chown guillaume:connaispas "./Documentaires/The_Big_One_-_Michael_Moore.avi"
chown guillaume:connaispas "./Documentaires/Albert_Einstein____Comment_je_vois_le_Monde.avi"
chown guillaume:connaispas "./Documentaires/The Collective Evolution III_ The Shift _ Official Release 2014 - YouTube [360p].mp4"
chown guillaume:connaispas "./Documentaires/Einstein, le mystère de l'horloge & la théorie de la relativité ( Arte 2005 ).avi"
chown guillaume:connaispas "./Documentaires/Un_Jour_Sur_Terre"
chown guillaume:connaispas "./Documentaires/Un_Jour_Sur_Terre/Video a voir en DEUXIEME.avi"
chown guillaume:connaispas "./Documentaires/Un_Jour_Sur_Terre/Un.Jour.Sur.Terre.avi"
chown guillaume:connaispas "./Documentaires/L'Incroyable Vérite -le documentaire qui dérange - Documentaire Français.mp4"
chown guillaume:connaispas "./Documentaires/Démocratie-#DATAGUEULE.mkv"

chown guillaume:connaispas "./Enfants/La_Petite_Souris"
chown guillaume:connaispas "./Enfants/La_Petite_Souris/La.Petite.Souris_2.avi"
chown guillaume:connaispas "./Enfants/La_Petite_Souris/La.Petite.Souris.avi"
chown guillaume:connaispas "./Enfants/Escape_from_Planet_Earth.avi"
chown guillaume:connaispas "./Enfants/Ernest_et_Celestine.avi"
chown guillaume:connaispas "./Enfants/9.avi"

chown guillaume:connaispas "./English/Fahrenheit_451.mp4"
chown guillaume:connaispas "./English/Green_Solyent"
chown guillaume:connaispas "./English/Green_Solyent/Soleil_Vert__vostfr.srt"
chown guillaume:connaispas "./English/Green_Solyent/Soleil_Vert__vostfr.avi"
chown guillaume:connaispas "./English/Batman__The_Dark_Knight__VO.mp4"
chown guillaume:connaispas "./English/Imitation_Game.srt"
chown guillaume:connaispas "./English/Falling_Down.mp4"
chown guillaume:connaispas "./English/Cloud_Atlas.avi"

chown guillaume:connaispas "./English/Mr_Robot"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E04-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E08-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E10-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E02-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E01-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E07-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E05-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E03-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E09-VOSTFR.avi"
chown guillaume:connaispas "./English/Mr_Robot/Mr_Robot-SO1_E06-VOSTFR.avi"

chown guillaume:connaispas "./English/Criminal.mp4"
chown guillaume:connaispas "./English/Imitation_Game.mp4"
chown guillaume:connaispas "./English/Criminal.srt"

chown guillaume:connaispas "./Espionnage/Une_Affaire_d_Etat.avi"

chown guillaume:connaispas "./Genre/Va vis et deviens.com.avi"
chown guillaume:connaispas "./Genre/Romantique/La_Couleur_des_Sentiments.avi"
chown guillaume:connaispas "./Genre/Romantique/Paper.Towns.avi"
chown guillaume:connaispas "./Genre/Romantique/Dans_La_Peau_D'une_Blonde.avi"
chown guillaume:connaispas "./Genre/Romantique/Dirty_Dancing.avi"
chown guillaume:connaispas "./Genre/Romantique/Dans_Ses_Yeux.avi"
chown guillaume:connaispas "./Genre/Romantique/Parle_avec_Elle.avi"
chown guillaume:connaispas "./Genre/Romantique/N.oublie.Jamais.avi"
chown guillaume:connaispas "./Genre/Romantique/Jamais.Le.Premier.Soir.avi"
chown guillaume:connaispas "./Genre/Romantique/La_Main_Au_Collier.avi"
chown guillaume:connaispas "./Genre/Romantique/Le_Coeur_des_Hommes.avi"
chown guillaume:connaispas "./Genre/The_Book_of_Henry.avi"
chown guillaume:connaispas "./Genre/Les.Souvenirs.avi"
chown guillaume:connaispas "./Genre/Les_Figures_de_l_Ombre.avi"
chown guillaume:connaispas "./Genre/YesMan.avi"
chown guillaume:connaispas "./Genre/Vipère Au Poing.avi"
chown guillaume:connaispas "./Genre/Les_Jardins_du_Roi.mkv"
chown guillaume:connaispas "./Genre/L Homme qui voulait vivre sa vie.avi"
chown guillaume:connaispas "./Genre/Les Risques Du Metier.avi"
chown guillaume:connaispas "./Genre/Bread_and_Roses.avi"
chown guillaume:connaispas "./Genre/sexfriends.avi"
chown guillaume:connaispas "./Genre/Ni_Pour_ni_Contre.avi"
chown guillaume:connaispas "./Genre/Dramatique/La_Traversee_de_Paris.avi"
chown guillaume:connaispas "./Genre/Dramatique/Entre_Deux_Rives.avi"
chown guillaume:connaispas "./Genre/Dramatique/La_tete_en_Friche.avi"
chown guillaume:connaispas "./Genre/Dramatique/Dialogue_Avec_Mon_Jardinier.avi"
chown guillaume:connaispas "./Genre/Dramatique/Les Chariots De Feu.avi"
chown guillaume:connaispas "./Genre/Dramatique/Irreversible.avi"
chown guillaume:connaispas "./Genre/Dramatique/La_derniere_Marche.avi"
chown guillaume:connaispas "./Genre/Dramatique/La_Mome.avi"
chown guillaume:connaispas "./Genre/Dramatique/Sept_Vies.avi"
chown guillaume:connaispas "./Genre/Dramatique/La.Journee.De.La.Jupe.avi"
chown guillaume:connaispas "./Genre/Dramatique/Un Monde Parfait.avi"
chown guillaume:connaispas "./Genre/Dramatique/Still.Alice.avi"
chown guillaume:connaispas "./Genre/Dramatique/Ecrire_pour_Exister.avi"
chown guillaume:connaispas "./Genre/Dramatique/Le_Majordome.avi"
chown guillaume:connaispas "./Genre/Dramatique/De_Battre_mon_Coeur_s_est_arrete.avi"
chown guillaume:connaispas "./Genre/Dramatique/12_Hommes_en_Colère.mkv"
chown guillaume:connaispas "./Genre/Dramatique/Le_Parfum.avi"
chown guillaume:connaispas "./Genre/Dramatique/L_Homme_Qui_Voulait_Vivre_sa_Vie.avi"
chown guillaume:connaispas "./Genre/Dramatique/Douze_Hommes_En_Colere.avi"
chown guillaume:connaispas "./Genre/Game_Night.avi"
chown guillaume:connaispas "./Genre/Mensonges_et_Trahison.avi"

chown guillaume:connaispas "./Historique/Agora.avi"

chown guillaume:connaispas "./Horreur/Land_of_The_Dead.avi"
chown guillaume:connaispas "./Horreur/BrainDead.avi"
chown guillaume:connaispas "./Horreur/The_Eye.avi"
chown guillaume:connaispas "./Horreur/The_Possession.avi"
chown guillaume:connaispas "./Horreur/Diary_Of_The_Dead.avi"
chown guillaume:connaispas "./Horreur/La_Collline_a_des_Yeux.avi"
chown guillaume:connaispas "./Horreur/Alone_In_The_Dark.avi"

chown guillaume:connaispas "./Humour/La_Folle_Journee_de_Ferris_Buller.avi"
chown guillaume:connaispas "./Humour/Ils_se_marierent_et_eurent_beaucoup_d_enfants.avi"
chown guillaume:connaispas "./Humour/L_Auberge-Rouge.avi"
chown guillaume:connaispas "./Humour/Les_Hommes_Viennent_De_Mars_Et_Les_Femmes_De_Venus.avi"
chown guillaume:connaispas "./Humour/South_Park-Le_Film.avi"
chown guillaume:connaispas "./Humour/Why.Men.Dont.Listen.And.Women.Cant.Read.Maps-JSK.avi"

chown guillaume:connaispas "./Policier/Omar_m_a_Tuer.avi"
chown guillaume:connaispas "./Policier/Edison.avi"
chown guillaume:connaispas "./Policier/Showtime.avi"
chown guillaume:connaispas "./Policier/Braquage_a_l_Italienne.avi"
chown guillaume:connaispas "./Policier/Message.from.the.King.avi"
chown guillaume:connaispas "./Policier/L_Ordre_Et_La_Morale.avi"
chown guillaume:connaispas "./Policier/Les_Lyonnais.avi"

chown guillaume:connaispas "./Politique/Battle_in_Seattle.avi"
chown guillaume:connaispas "./Politique/The_Elephant_in_the_Room.mp4"
chown guillaume:connaispas "./Politique/Joint_Security_Area.avi"
chown guillaume:connaispas "./Politique/Painful_Deceptions.avi"
chown guillaume:connaispas "./Politique/Le_Monde_Selon_Bush.avi"
chown guillaume:connaispas "./Politique/Parvana.avi"
chown guillaume:connaispas "./Politique/WilliamRodriguezAmer.avi"
chown guillaume:connaispas "./Politique/9-11__Press_for_Truth.avi"
chown guillaume:connaispas "./Politique/Goldman Sachs - La banque qui dirige le monde.mp4"
chown guillaume:connaispas "./Politique/ZERO__Enquête_sur_le_11_Septembre.mp4"
chown guillaume:connaispas "./Politique/Le President (Jean Gabin).avi"
chown guillaume:connaispas "./Politique/Too.Big.To.Fail.avi"
chown guillaume:connaispas "./Politique/Painful DeceptionsUpdate 911 Commission Report.wmv"

chown guillaume:connaispas "./Science-Fiction/The_Jacket.avi"
chown guillaume:connaispas "./Science-Fiction/Attraction.avi"
chown guillaume:connaispas "./Science-Fiction/The Man From Earth.avi"
chown guillaume:connaispas "./Science-Fiction/The_Prodigies.avi"
chown guillaume:connaispas "./Science-Fiction/Synchronicity.avi"
chown guillaume:connaispas "./Science-Fiction/Battle_Los_Angeles.avi"
chown guillaume:connaispas "./Science-Fiction/Fahrenheit_451.avi"
chown guillaume:connaispas "./Science-Fiction/Predestination.avi"

chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_9.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_12.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_9.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_7.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_12.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_14.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_7.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_5.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_6.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_12.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_3.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_6.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_4.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_1.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_2.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_10.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_1.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_5.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_2.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_5.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_11.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_1.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_12.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_8.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_9.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_11.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_8.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_5.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_13.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_2.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_9.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_3.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_4.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_15.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_11.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_8.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_6.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_2.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_10.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_4.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_8.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_7.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_10.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_4.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_10.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_2_Episode_3.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_4_Episode_3.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_6.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_11.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_16.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_1.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_5_Episode_13.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_7.avi"
chown guillaume:connaispas "./Series/Breaking_Bad/Breaking_Bad~^~Saison_3_Episode_13.avi"

chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E03.FRENCH.HDTV.XviD-ZT.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E13.FiNAL.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E02.FRENCH.HDTV.XviD-ZT.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E08.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E04.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E11.FRENCH.HDTV.XviD-ASPHiXiAS.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E07.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E10.FRENCH.HDTV.XviD-ASPHiXiAS.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E12.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E01.FRENCH.HDTV.XviD-ZT.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E05.FRENCH.HDTV.XviD-ZT.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.The.Dome.S02E13.FiNAL.FRENCH.LD.HDTV.XviD-ASPHiXiAS.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E06.FRENCH.HDTV.XviD-ZT.zone-telechargement.com.avi"
chown guillaume:connaispas "./Series/Under_the_Dome__S3_VOSTFR/Under.the.Dome.S03E09.FRENCH.HDTV.XviD-ARK01.zone-telechargement.com.avi"

chown guillaume:connaispas "./Series/Sex_And_The_City___The_Movie"
chown guillaume:connaispas "./Series/Sex_And_The_City___The_Movie/Sex_And_The_City_The_Movie___CD1.avi"
chown guillaume:connaispas "./Series/Sex_And_The_City___The_Movie/Sex_And_The_City_The_Movie___CD2.avi"

chown guillaume:connaispas "./Series/Death_Note/Death Note 13 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 17 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 02.Confrontation.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 25 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 27 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 11 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 22 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 23 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 08.Regard.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 31 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 21 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 10.Doute.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 20.FRENCH.HDTV.By.PeaceMaker.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 37 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 26 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 36 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 06.Déchirure.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 01.Renaissance.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 05.Tactique.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 29 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 18 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 28 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 04.Poursuite.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 07.Temps.Couvert.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 09.Contact.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 03.Pacte.FR.HDTV-EIZO.[tvu.org.ru].avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 19 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 33 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 15 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 14.FRENCH.HDTV.By.PeaceMaker.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 16 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 30.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 34 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 35 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 24 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 12 vf by Mugiwara www.tunisia-sat.com.avi"
chown guillaume:connaispas "./Series/Death_Note/Death Note 32 vf by Mugiwara www.tunisia-sat.com.avi"

chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Le_coeur_a_ses_raisons.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Episode_6.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Pour_les_anges.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~L'auto-stoppeur.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Peine_capitale.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~C_est_Une_Belle_Vie.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Cauchemar_a_20000_Pieds.avi"
chown guillaume:connaispas "./Series/Twillight_Zone/The_Twillight_Zone~^~Les_Trois_Fantomes.avi"

chown guillaume:connaispas "./Series/Walking_Dead"
chown guillaume:connaispas "./Series/Walking_Dead/the.walking.dead.s01e05.avi"
chown guillaume:connaispas "./Series/Walking_Dead/the.walking.dead.s01e02.avi"
chown guillaume:connaispas "./Series/Walking_Dead/the.walking.dead.s01e04.avi"
chown guillaume:connaispas "./Series/Walking_Dead/the.Walking.Dead.S01E03.avi"
chown guillaume:connaispas "./Series/Walking_Dead/the.walking.dead.s01e06.final.avi"
chown guillaume:connaispas "./Series/Walking_Dead/the.walking.dead.s01e01.avi"

chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_1.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_8.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_3.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_4.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_2.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_7.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_6.avi"
chown guillaume:connaispas "./Series/House_of_Cards/House_of_Cards~^~Saison_1_Episode_5.avi"

chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_12.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_03.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_11.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_07.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_06.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_08.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_09.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_04.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_10.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_02.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_05.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_2/True_Blood~^~Saison_2_Episode_01.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_01.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_10.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_03.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_08.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_09.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_04.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_12.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_07.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_11.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_02.avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_06..avi"
chown guillaume:connaispas "./Series/True_Blood/Saison_1/True_Blood~^~Saison_1_Episode_05.avi"

chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_07.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_03.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_04.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_08.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_06.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_05.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_09.avi"
chown guillaume:connaispas "./Series/Mr.Robot/Mr_Robot~^~Saison_1_Episode_10.avi"

chown guillaume:connaispas "./Series/FlashForward_Saison_1_VOSTFR/FlashForward~^~Saison_1~^~Episode_09.Believe.avi"
chown guillaume:connaispas "./Series/FlashForward_Saison_1_VOSTFR/FlashForward~^~Saison_1~^~Episode_07.The.Gift.avi"
chown guillaume:connaispas "./Series/FlashForward_Saison_1_VOSTFR/FlashForward~^~Saison_1~^~Episode_06.Scary.Monsters.And.Super.Creeps.avi"
chown guillaume:connaispas "./Series/FlashForward_Saison_1_VOSTFR/FlashForward~^~Saison_1~^~Episode_08.Playing.Cards.With.Coyote.avi"
chown guillaume:connaispas "./Series/FlashForward_Saison_1_VOSTFR/FlashForward~^~Saison_1~^~Episode_05.Gimme.Some.Truth.avi"

chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_08.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_03.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_04.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_07.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_10.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_02.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_01.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_09.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_06.avi"
chown guillaume:connaispas "./Series/Le_Bureau_des_Legendes/Le_Bureau_Des_Legendes~^~Saison_1_Episode_05.avi"

chown guillaume:connaispas "./Spectacle_Musical/The_Cure_Trilogy"
chown guillaume:connaispas "./Spectacle_Musical/The_Cure_Trilogy/The_Cure_Trilogy_Disc2.mkv"
chown guillaume:connaispas "./Spectacle_Musical/The_Cure_Trilogy/The_Cure_Trilogy_Disc1.mkv"
chown guillaume:connaispas "./Spectacle_Musical/ABBA Super Troupers.avi"
chown guillaume:connaispas "./Spectacle_Musical/Fantastica Instrumenta.wmv"

chown guillaume:connaispas "./Temp/Bataille_a_Seattle.mkv"
chown guillaume:connaispas "./Temp/Mary_Shelley.avi"
chown guillaume:connaispas "./Temp/Safari.avi"
chown guillaume:connaispas "./Temp/My_Pet_Dinosaur.avi"
chown guillaume:connaispas "./Temp/Les_Souvenirs.avi"
chown guillaume:connaispas "./Temp/Par_Suite_d_un_Arrêt_de_Travail.avi"
chown guillaume:connaispas "./Temp/Jennifer_s_Body.avi"
chown guillaume:connaispas "./Temp/Tschernobyl_Diaries.avi"
chown guillaume:connaispas "./Temp/L_Ordre_du_Loup.avi"
chown guillaume:connaispas "./Temp/Dikkenek.avi"
chown guillaume:connaispas "./Temp/Echelon_Conspiracy.avi"
chown guillaume:connaispas "./Temp/BlackHat.avi"
chown guillaume:connaispas "./Temp/120_Battements_par_Minute.avi"
chown guillaume:connaispas "./Temp/Mary_and_Max.avi"
chown guillaume:connaispas "./Temp/Renaissance.avi"
chown guillaume:connaispas "./Temp/Meet_Dave.avi"
chown guillaume:connaispas "./Temp/Martian_Child.avi"
chown guillaume:connaispas "./Temp/Blair_Witch_2016.avi"
chown guillaume:connaispas "./Temp/A_Sound_of_Thunder.avi"
chown guillaume:connaispas "./Temp/Tracks.avi"
chown guillaume:connaispas "./Temp/The_Guernsey_Literary.mkv"
chown guillaume:connaispas "./Temp/Saute_Mouton.avi"
chown guillaume:connaispas "./Temp/Empire_State.avi"
chown guillaume:connaispas "./Temp/Bande_de_Sauvages.avi"
chown guillaume:connaispas "./Temp/Implacable.avi"
chown guillaume:connaispas "./Temp/Marley_et_Moi.avi"
chown guillaume:connaispas "./Temp/Chrysalis.avi"
chown guillaume:connaispas "./Temp/Passengers.avi"
chown guillaume:connaispas "./Temp/L_Ecole_est_Finie.avi"
chown guillaume:connaispas "./Temp/Agathe_Clery.avi"
chown guillaume:connaispas "./Temp/Larguees.avi"
chown guillaume:connaispas "./Temp/Problemos.avi"
chown guillaume:connaispas "./Temp/Detachment.avi"
chown guillaume:connaispas "./Temp/Requiem_for_a_Dream.avi"
chown guillaume:connaispas "./Temp/Le_Dernier_Vice-Roi_des_Indes.avi"
chown guillaume:connaispas "./Temp/N_Oublie_Jamais.avi"
chown guillaume:connaispas "./Temp/The_Postman.avi"
chown guillaume:connaispas "./Temp/Mondwest.avi"
chown guillaume:connaispas "./Temp/N_importe_Qui.avi"
chown guillaume:connaispas "./Temp/Flood.avi"
chown guillaume:connaispas "./Temp/Going_in_Style.avi"
chown guillaume:connaispas "./Temp/Voyoucratie.mkv"
chown guillaume:connaispas "./Temp/La_Mission_du_Lynx.avi"
chown guillaume:connaispas "./Temp/Dying_of_the_Light.avi"
chown guillaume:connaispas "./Temp/Le_Grand_Mechant_Renard_et_autres_Contes.avi"
chown guillaume:connaispas "./Temp/Stupeur_et_Tremblements.avi"
chown guillaume:connaispas "./Temp/Alceste_a_Bicyclette.avi"
chown guillaume:connaispas "./Temp/Revolt.avi"
chown guillaume:connaispas "./Temp/Les_Etoiles_Restantes.avi"
chown guillaume:connaispas "./Temp/Amours_Chiennes.avi"
chown guillaume:connaispas "./Temp/Melancolie_Ouvriere.avi"
chown guillaume:connaispas "./Temp/Le_Brio.avi"
chown guillaume:connaispas "./Temp/Malcolm.avi"
chown guillaume:connaispas "./Temp/Les_Hommes_du_Feu.avi"
chown guillaume:connaispas "./Temp/Ce_qui_nous_lie.avi"
chown guillaume:connaispas "./Temp/Insiders.avi"
chown guillaume:connaispas "./Temp/L'Homme_Orchestre.avi"
chown guillaume:connaispas "./Temp/Revelations.avi"
chown guillaume:connaispas "./Temp/Bird.mkv"
chown guillaume:connaispas "./Temp/Tom_Sawyer.avi"
chown guillaume:connaispas "./Temp/First_Snow.avi"
chown guillaume:connaispas "./Temp/The_Women.avi"
chown guillaume:connaispas "./Temp/Rings.avi"
chown guillaume:connaispas "./Temp/Un_Français.avi"
chown guillaume:connaispas "./Temp/Une_Famille_Syrienne.avi"
chown guillaume:connaispas "./Temp/Let_the_Sunshine_In.avi"
chown guillaume:connaispas "./Temp/Goodbye_Bafana.avi"
chown guillaume:connaispas "./Temp/Vatel.avi"
chown guillaume:connaispas "./Temp/La_Belle_Saison.avi"
chown guillaume:connaispas "./Temp/Invictus.mkv"
chown guillaume:connaispas "./Temp/La_Fille_de_Brest.avi"
chown guillaume:connaispas "./Temp/The_Theory_of_Everything_VOSTFR.avi"
chown guillaume:connaispas "./Temp/Crazy_Amy.avi"
chown guillaume:connaispas "./Temp/Le_Prenom.avi"
chown guillaume:connaispas "./Temp/Le_Premier_Cri.avi"
chown guillaume:connaispas "./Temp/Nos_Jours_Heureux.avi"
chown guillaume:connaispas "./Temp/Three_Billboards.avi"
chown guillaume:connaispas "./Temp/Les_Virtuoses.avi"
chown guillaume:connaispas "./Temp/It.avi"

chown guillaume:connaispas "./Thriller/Blindness.avi"
chown guillaume:connaispas "./Thriller/Basic.avi"
chown guillaume:connaispas "./Thriller/Intersections.avi"
chown guillaume:connaispas "./Thriller/Prédictions.avi"
chown guillaume:connaispas "./Thriller/Complots.mkv"

