#!/bin/bash

# ============================================================================================================================================================= #
# Script de vérification de sommes MD5/SHA-1/SHA-256, version 4.0.5 par Cooleech
# Envoyer un courriel à: cooleech@gmail.com
# French by Ludovic Troisi
# ============================================================================================================================================================= #

AppVer="4.0.5"
HConFile="$HOME/.HashCheck/HC.conf"
SavedSettings=`cat $HConFile`

which xdg-user-dirs-update
if [ $? = 0 ]; then
.	~/.config/user-dirs.dirs # Import variables
fi

# Set desktop icon dir
if [ "$XDG_DESKTOP_DIR" = "" ]; then
	if [ -d "$HOME/Desktop" ]; then
		XDG_DESKTOP_DIR="$HOME/Desktop"
	else
		XDG_DESKTOP_DIR="$HOME"
	fi
fi

if [ -e $HConFile ]; then
.	$HConFile # Import variables
fi

if [ "$1" = "" ]; then
	SelectedFile=`zenity --title="Choisissez un fichier à vérifier" --file-selection`
fi

if [ "$SelectedFile" = "" ]; then
	if [ $# -gt 1 ]; then
		zenity --error --text="Vous devez choisir un fichier !"
		exit 1
	fi
	if [ "$1" = "" ]; then
		exit 1
	fi
fi

if [ -d "$1" ]; then
	zenity --error --text="<b>$1</b> est un répertoire.
Ce script ne fonctionne pas avec les répertoires !"
	exit 1
fi

if [ "$SelectedFile" = "" ]; then
	SelectedFile="$1"
fi

SelectedFileNameFix="${SelectedFile//'&'/&amp;}" # Fix for ampersand simbol

if [ `stat --printf="%s" "$SelectedFile"` = "0" ]; then
	zenity --warning --text="<b>$SelectedFileNameFix</b> est vide (0 bytes) !
Il est inutile de vérifier la somme de ce fichier !"
	exit 1
fi

if [ -d "${SelectedFile%/*}" ]; then # Check if dir or file
	FileNoPath="${SelectedFileNameFix##*/}"
	FilePath="${SelectedFile%/*}/" # md5sum, sha1sum and sha256sum need file path
else
	FileNoPath="$SelectedFileNameFix"
	FilePath="./" # md5sum, sha1sum and sha256sum need file path
fi

function DELETE_OLD_HASH_FILE {
zenity --question --title="Hash Checker $AppVer" --text="Un ancien fichier de vérification de somme trouvé:\n<b>$FileNoPath$HashFile</b>\n\nVoulez-vous l'effacer (recommandé) ?" \
			
if [ $? = 0 ]; then
	rm -f "$SelectedFile$HashFile" # Must keep path
fi
}

if [ -e "$SelectedFile"_md5.txt ]; then # Must keep path
	HashFile="_md5.txt"
	DELETE_OLD_HASH_FILE
fi

if [ -e "$SelectedFile"_sha1.txt ]; then # Must keep path
	HashFile="_sha1.txt"
	DELETE_OLD_HASH_FILE
fi

if [ -e "$SelectedFile"_sha256.txt ]; then # Must keep path
	HashFile="_sha256.txt"
	DELETE_OLD_HASH_FILE
fi

# Get last states
if [ "$MD5_HASH_CHECKED" = "" ]; then
	MD5state="TRUE"
else
	MD5state="$MD5_HASH_CHECKED"
fi

if [ "$SHA1_HASH_CHECKED" = "" ]; then
	SHA1state="FALSE"
else
	SHA1state="$SHA1_HASH_CHECKED"
fi

if [ "$SHA256_HASH_CHECKED" = "" ]; then
	SHA256state="FALSE"
else
	SHA256state="$SHA256_HASH_CHECKED"
fi

if [ "$SAVE_TO_TEXT_FILE" = "" ]; then
	TextFileState="FALSE"
else
	TextFileState="$SAVE_TO_TEXT_FILE"
fi

if [ -r "$SelectedFile" ]; then
	TypeOfHash=`zenity --width=400 --height=250 --list --checklist --title="Hash Checker $AppVer" --text="Choisissez un type de vérification pour le fichier <b>$FileNoPath</b>" \
			--column "Cocher" --column "le type désiré" $MD5state MD5 $SHA1state SHA1 $SHA256state SHA256 $TextFileState "Enregistrer le résultat de l'empreinte en fichier texte"`
else
	zenity --error --text "Vous n'êtes pas autorisé à lire ce fichier !"
	exit 1
fi

if ! [ -e "$SelectedFile" ]; then
	zenity --error --text "Impossible de trouver le fichier <b>$FileNoPath</b> !\nCe fichier a été renommé, déplacé ou supprimé !"
	exit 1
fi
# Reset all
MD5state="FALSE"
SHA1state="FALSE"
SHA256state="FALSE"
TextFileState="FALSE"

case $TypeOfHash in
MD5*) # MD5 with any other
MD5state="TRUE"
(
echo "# Somme MD5 en cours de vérification. Selon la taille du fichier '$FileNoPath',\nla vitesse du disque et du CPU, le processus peut être long. Veuillez patienter..."
md5sum "$SelectedFile" >> /tmp/"$FileNoPath"_md5.txt
) | zenity --width="400" --progress --title="Somme MD5 en cours de vérification" --text="" --percentage=0 --auto-close --pulsate
esac

case $TypeOfHash in
*SHA1*) # SHA1 with any other
SHA1state="TRUE"
(
echo "# Somme SHA1 en cours de vérification. Selon la taille du fichier '$FileNoPath',\nla vitesse du disque et du CPU, le processus peut être long. Veuillez patienter..."
sha1sum "$SelectedFile" >> /tmp/"$FileNoPath"_sha1.txt
) | zenity --width="400" --progress --title="Somme SHA1 en cours de vérification" --text="" --percentage=0 --auto-close --pulsate
esac

case $TypeOfHash in
*SHA256*) # SHA256 with any other
SHA256state="TRUE"
(
echo "# Somme SHA256 en cours de vérification. Selon la taille du fichier '$FileNoPath',\nla vitesse du disque et du CPU, le processus peut être long. Veuillez patienter..."
sha256sum "$SelectedFile" >> /tmp/"$FileNoPath"_sha256.txt
) | zenity --width="400" --progress --title="Somme SHA256 en cours de vérification" --text="" --percentage=0 --auto-close --pulsate
esac

case $TypeOfHash in
*Enregistrer*)
TextFileState="TRUE"
esac

case $TypeOfHash in
"") # No selection
exit 1
esac

CurrentSettings="# HASH CHECKER SETTINGS

MD5_HASH_CHECKED=$MD5state
SHA1_HASH_CHECKED=$SHA1state
SHA256_HASH_CHECKED=$SHA256state
SAVE_TO_TEXT_FILE=$TextFileState"

if [ ! "$SavedSettings" = "$CurrentSettings" ]; then
	echo "$CurrentSettings" > $HConFile
fi

if [ -e /tmp/"$FileNoPath"_md5.txt ]; then
	MD5hash=`cat /tmp/"$FileNoPath"_md5.txt`
	MD5WithoutPath="${MD5hash%%  $SelectedFile}"
else
	MD5WithoutPath="N/A"
fi

if [ -e /tmp/"$FileNoPath"_sha1.txt ]; then
	SHA1hash=`cat /tmp/"$FileNoPath"_sha1.txt`
	SHA1WithoutPath="${SHA1hash%%  $SelectedFile}"
else
	SHA1WithoutPath="N/A"
fi

if [ -e /tmp/"$FileNoPath"_sha256.txt ]; then
	SHA256hash=`cat /tmp/"$FileNoPath"_sha256.txt`
	SHA256WithoutPath="${SHA256hash%%  $SelectedFile}"
else
	SHA256WithoutPath="N/A"
fi

if [ "$TextFileState" = "TRUE" ]; then
	if [ -e /tmp/"$FileNoPath"_md5.txt ]; then
		mv /tmp/"$FileNoPath"_md5.txt "$SelectedFile"_md5.txt
	fi
	if [ -e /tmp/"$FileNoPath"_sha1.txt ]; then
		mv /tmp/"$FileNoPath"_sha1.txt "$SelectedFile"_sha1.txt
	fi
	if [ -e /tmp/"$FileNoPath"_sha256.txt ]; then
		mv /tmp/"$FileNoPath"_sha256.txt "$SelectedFile"_sha256.txt
	fi
fi

zenity --question --title="Hash Checker $AppVer" --no-wrap --text="Fichier: <b>$FileNoPath</b>
\nMD5 hash: <b>$MD5WithoutPath</b>\nSHA1 hash: <b>$SHA1WithoutPath</b>\nSHA256 hash: <b>$SHA256WithoutPath</b>\n
Voulez-vous ouvrir votre navigateur pour comparer les sommes ?"

if [ $? = 0 ]; then
	case $TypeOfHash in
	MD5*)
	SearchString="$MD5WithoutPath  "
	esac
	case $TypeOfHash in
	*SHA1*)
	SearchString="$SearchString$SHA1WithoutPath  "
	esac
	case $TypeOfHash in
	*SHA256*)
	SearchString="$SearchString$SHA256WithoutPath  "
	esac
	SearchString="$SearchString$FileNoPath"
	which xdg-user-dirs-update
	if [ $? = 0 ]; then
		xdg-open "http://www.google.com/search?q=$SearchString"
	else
		zenity --error --text "ERROR: NO XUD"
	fi
fi

# Cleanup /tmp
if [ -e /tmp/"$FileNoPath"_md5.txt ]; then
	rm -f /tmp/"$FileNoPath"_md5.txt
fi
if [ -e /tmp/"$FileNoPath"_sha1.txt ]; then
	rm -f /tmp/"$FileNoPath"_sha1.txt
fi
if [ -e /tmp/"$FileNoPath"_sha256.txt ]; then
	rm -f /tmp/"$FileNoPath"_sha256.txt
fi

exit 0

# =========================================================== Created using Setup v3.4 by Cooleech ============================================================ #
